# Generated by Django 5.2.3 on 2025-06-19 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='загрузите видео', null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='опишите курс', max_length=250, null=True, verbose_name='описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='укажите название курса', max_length=100, verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='edu_materials/previews', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='выберите курс', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_set', to='edu_materials.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='опишите урок', max_length=250, null=True, verbose_name='описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='укажите название урока', max_length=100, verbose_name='название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='edu_materials/pictures', verbose_name='картинка'),
        ),
    ]
